### ISSUE TITLE
Creazione evento pubblico

### ISSUE THREAD

**Issue by ElBlasco69** [marck283/EventManager#44]
**Describe the bug**
Dopo aver effettuato il log in con google non è possibile creare un evento pubblico, appare un pop up che indica che la data è mancante

**To Reproduce**
1. Log In con google
2. Creazione evento pubblico
3. Errore di mancanza data

**Expected behavior**
Creazione dell'evento

**Desktop (please complete the following information):**
 - Browser: Firefox 106.0.1

**Comment by marck283** [comment]
Ok dovrei aver risolto il problema. Il bug in questione era dovuto ad un errore di programmazione dell'UI. Finisco di integrare le ultime modifiche e poi aggiorno il sistema. Ti avviserò quando avrò finito.
